# Generated by Django 4.1.5 on 2023-03-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendances',
            new_name='Attendance',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
