# Generated by Django 4.1.5 on 2023-03-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_rename_attendances_attendance_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='./static/users/images'),
        ),
    ]
