# Generated by Django 4.1.5 on 2023-03-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0005_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='attendances/static/users/images'),
        ),
    ]
